# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "PJs Job"

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureStaticWebApp@0
  name: "Static_Deploy"
  inputs:
    app_location: '/'
    api_location: 'api'
    azure_static_web_apps_api_token: $(hs-static-web-app-token)
