# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "PJs Job"

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
- script: |
    npm install
  displayName: 'npm install'
- script: |
    npm run build
  displayName: 'npm build'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      src/*
      public/*
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Project Files'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ttrpg-companion-ui.zip'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'ttrpg-companion-ui'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'PJs Azure Subscription(4f21ac75-d99a-498a-972a-c4be490a2f04)'
    appType: 'webAppLinux'
    appName: 'ttrpg-companion'
    package: 'pipeline/ttrpg-companion-ui.zip'
    runtimeStack: 'NODE|18-lts'